llm:
    gemini:
          provider: "gemini"
          model_name: "gemini-3-pro-preview"
    openai:
          provider: "openai"
          model_name: "o4-mini"
    groq:
          provider: "groq"
          model_name: "openai/gpt-oss-120b"